---
- name: Hardening for CentOS
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Cai dat repo
      yum: name=epel-release state=present

    - name: Cai dat nhung dich vu can thiet
      yum: 
        name:
          - openssh-server
          - firewalld
          - fail2ban
          - audit
          - rsyslog
          - vim
          - bind-utils
          - wget
          - authconfig
          - tmux
          - htop
        state: present

    - name: Go cai dat nhung dich vu khong can thiet
      yum:
        name:
          - ypserv
          - ypbind
          - rsh-server
          - rsh
          - talk-server
          - talk
          - tftp-server
          - tftp
          - telnet-server
          - xinetd
          - rsyncd
          - xorg-x11
          - avahi-daemon
          - dhcpd
          - nfs-server
          - nfs 
          - vsftpd
          - dovecot
          - samba
          - squid
          - bind
          - net-snmp
        state: absent

    - name: Khoi dong nhung dich vu can thiet
      service: name="{{ item }}" state=started enabled=yes
      with_items:
          - sshd
          - firewalld
          - fail2ban
          - rsyslog

    - name: Tao Banner cho dich vu SSH
      lineinfile: line="{{ item }}" create=true path=/etc/ssh/citigo-banner
      with_items: 
          - /---------------------------------------------------------------/
          - /                     *** WARNING LOGIN***                      /
          - /        Welcome to CITIGO SOFTWARE JOINT STOCK COMPANY         /
          - /         All connections are monitored and recorded            /
          - /   Disconnect IMMEDIATELY if you are not an authorized user!   /
          - /+-------------------------------------------------------------+/
          
    - name: Thay doi cau hinh dich vu SSH
      command: echo -n " " > /etc/ssh/sshd_config
      lineinfile: line="{{ item }}" create=true path=/etc/ssh/sshd_config
      with_items:
          - # Version and Port
          - Protocol 2
          - Port 22
          - # Allow use private key
          - HostKey /etc/ssh/ssh_host_rsa_key
          - HostKey /etc/ssh/ssh_host_ecdsa_key
          - HostKey /etc/ssh/ssh_host_ed25519_key
          - # Logging
          - SyslogFacility AUTHPRIV
          - LogLevel VERBOSE
          - # Authentication:
          - ClientAliveInterval 600
          - ClientAliveCountMax 0
          - LoginGraceTime 30s
          - PermitRootLogin no
          - MaxAuthTries 3
          - MaxSessions 2
          - PubkeyAuthentication yes
          - AuthorizedKeysFile	.ssh/authorized_keys
          - IgnoreRhosts yes
          - HostbasedAuthentication no
          - PermitEmptyPasswords no
          - PermitUserEnvironment no
          - PasswordAuthentication yes
          - ChallengeResponseAuthentication no
          - UseDNS no
          - Ciphers "aes128-ctr,aes192-ctr,aes256-ctr"
          - # GSSAPI options
          - GSSAPIAuthentication yes
          - GSSAPICleanupCredentials no
          - # Config PAM
          - UsePAM yes
          - # Enable X11
          - X11Forwarding yes
          - # Banner BOS Securities
          - Banner /etc/ssh/citigo-banner
          - # Accept locale-related environment variables
          - AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
          - AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
          - AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
          - AcceptEnv XMODIFIERS
          - # Default subsystems
          - Subsystem	sftp	/usr/libexec/openssh/sftp-server

    - name: Thay doi quyen cua tep tin dich vu ssh
      file: path=/etc/ssh/sshd_config owner=root group=root mode='0600'

    - name: Khoi dong lai dich vu ssh
      service: name="sshd" state=started enabled=yes
