---
- name: Hardening for CentOS
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Cai dat repo
      yum: name=epel-release state=present

    - name: Cai dat nhung dich vu can thiet
      yum: 
        name:
          - openssh-server
          - firewalld
          - fail2ban
          - audit
          - rsyslog
          - vim
          - bind-utils
          - wget
          - authconfig
          - tmux
          - htop
        state: present

    - name: Khoi dong nhung dich vu can thiet
      service: name="{{ item }}" state=started enabled=yes
      with_items:
          - sshd
          - firewalld
          - fail2ban
          - rsyslog
