---
- name: Configure all servers.
  hosts: all
  become: yes
  tasks:
    - name: Install apache mod_php package.
      package:
        name: "httpd"
        state: present
      notify: restart httpd
